stages:
  - install
  - publish

cache: # 缓存
  paths: 
    - node_modules
    - dist

install-job:
  stage: install
  script:
    - npm install

publish-job:
  stage: publish
  script:
    - npm publish --registry http://110.42.187.35