stages:
  - install
  - publish

cache: # 缓存
  paths: 
    - node_modules
    - dist

install-job:
  tags:
    - tx_linux
  stage: install
  script:
    - npm install

install-job-info:
  tags:
    -tx_linux
  stage: install
  script:
    - ls -a

publish-job:
  tags:
    - tx_linux
  stage: publish
  script:
    - npm who am i
    - echo '----------------------'
    - npm publish --registry http://110.42.187.35:4873
  only:
    - master