stages:
  - install
  - build
  - publish

cache: # 缓存
  paths: 
    - node_modules
    - dist

install-job:
  tags:
    - tx_linux
  stage: install
  script:
    - npm install

build-job:
  tags:
    - tx_linux
  stage: build
  script:
    - npm run build

publish-job:
  tags:
    - tx_linux
  stage: publish
  script:
    - npm who am i
    - echo '----------------------'
    - npm publish --registry http://110.42.187.35:4873
  only:
    - master